#!/usr/bin/env python3

import re
import os
import sys
import random

the_list = "list.txt"
program_name = "nicethings"
top_line = "-----------------------------------------\n"
bottom_line = "\n-----------------------------------------"

messages = {'list_created': "{} created, try your command again and it should work :)".format(the_list),
            'list_empty': "sorry, there's nothing in {}\nTry adding something to the list by typing:\n{} \"your message here\"".format(the_list, program_name),
            'args_too_many': "Sorry, I only accept one argument.\nTry using:\n{} \"your message here\"".format(program_name),
            'input_null': "Sorry, I couldn't find any input.\n\nTry using:\n{} \"your message here\"".format(program_name),
            'item_added': "You have added the following to the list:\n",
            'try_again': "sorry, I didn't get that, try typing y or n:",
            'file_not_found': "{} doesn't exist\ndo you want me to make a {} file right now? (y/n)".format(the_list, the_list)}
            
def write_to_file(list_file, content):
    temp = open(list_file, 'a')
    temp.write(content)
    temp.close()

def create_file(list_file):
    open(list_file, 'a').close()
    print(messages['list_created'])

def show_random_line(list_file):
    thefile = open(list_file, 'r').read(1)
    temp = open(list_file, 'r')
    contents = temp.read(1)
    if not contents:
        print(messages['list_empty'])
    else:
        print(random.choice(list(open(the_list, 'r'))).rstrip('\n'))

def add_to_list():
    write_to_file(the_list, sys.argv[1] + "\n")
    print(top_line + messages['item_added'] + sys.argv[1] + bottom_line)

def hangle_args():
    if len(sys.argv) <= 1:
        show_random_line(the_list)
    elif len(sys.argv) > 2:
        too_many_args()
    elif sys.argv[1].isspace() == True or sys.argv[1] == "":
        print(messages['input_null'])
    else:
        add_to_list()

def prompt_file_creation():
    userchoice = input()
    if userchoice == "y":
        create_file(the_list)
    elif userchoice == "n":
        print("bye bye")
    else:
        print(messages['try_again'])
        prompt_file_creation()

def main():
    if os.path.exists(the_list) == True:
        hangle_args()
    else:
        print(messages['file_not_found'])
        prompt_file_creation()

if __name__ == '__main__':
    main()
